# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-9d04c278-8ff1-45d9-9fd1-52efc454e18b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-9d04c278-8ff1-45d9-9fd1-52efc454e18b".device = "/dev/disk/by-uuid/9d04c278-8ff1-45d9-9fd1-52efc454e18b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DFC7-DDDA";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-c8353ab7-a5b2-409d-bbfb-54baff97aca2"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
